NAME = "Ants turf war"
SCREENWIDTH, SCREENHEIGHT = 1200, 1000
ANTSIZE = 12
FIELDSIZE = ANTSIZE * 1.5
SCREENSIZE = (
    SCREENWIDTH - SCREENWIDTH % FIELDSIZE,
    SCREENHEIGHT - SCREENHEIGHT % FIELDSIZE,
)
GRIDCOLOR = "black"
ANTCOLOR = "wheat4"
