NAME = "Ants turf war"
SCREENWIDTH, SCREENHEIGHT = 1200, 1000
ANTSIZE = 12
FIELDSIZE = ANTSIZE * 1.5
SCREENSIZE = (
    SCREENWIDTH - SCREENWIDTH % FIELDSIZE,
    SCREENHEIGHT - SCREENHEIGHT % FIELDSIZE,
)
FONTSIZE = 36
BACKGROUNDCOLOR = "black"
GRIDCOLOR = (50, 50, 50)
ANTCOLOR = "wheat4"
